### ISSUE TITLE
Baby mobs appear at full grown size

### ISSUE THREAD

**Issue by GoombarioFan** [Derec-Mods/derecearthmod#36]
🐛 **Bug Report**
📝 Description
Baby versions of Minecraft Earth mobs appear at full grown size when spawned. As far as I know, all mobs that have can be babies have this issue. They also do not imprint onto adult mobs to follow them and instead seem to roam freely on their own. Despite having the adult appearance, the mobs still have a baby-sized hitbox and create higher pitched sounds.

⭐ Describe the solution you'd like
Baby Minecraft Earth mobs have proper scaled down models and proper baby mob behaviors.

🥟 How to reproduce?
Spawn any Minecraft Earth mob as a baby that can be spawned in as a baby.

🔢 Which version of the mod are you using?
1.16-2.0.1.3

❓ Anything else you would like to add? Comments? Info?
You're awesome!

**Comment by DereC4** [comment]
A known bug but might not be prioritized at the moment; I apologize for the model issues but I think the functionality should be the same which is why this issue will be put aside for now as I focus on more immediate bugs (like the misnaming you reported) 

(Also because i'm not that good with models... haha sorry)
