### ISSUE TITLE
Mobs still spawn even when "disable mob spawning" is set to true. 

### ISSUE THREAD

**Issue by Tanner201X** [Derec-Mods/derecearthmod#46]
🐛 **Bug Report**
📝 Description
When the gamerule "disable mob spawning" is set to true, Minecraft Earth mobs still continue to spawn. 

⭐ Describe the solution you'd like
When the gamerule is set to false, no mobs should spawn. 

🥟 How to reproduce?
Start a new world with the gamerule, "disable mob spawning" set to false. 

🔢 Which version of the mod are you using?
2.5.0.0

❓ Anything else you would like to add? Comments? Info?
You're awesome!

**Comment by DereC4** [comment]
Apologies for the delay but I've done some research and found that mobSpawning doesn't always work for modded entities or even some vanilla entities.
 
To quote, 

"doMobSpawning only affects "natural" spawning - mobs which randomly spawn given the right conditions, such as dark areas for hostile mobs and well-lighted grassy areas for passive mobs.

However, the majority of passive mobs (I believe ocelots are the only exception) spawn during world generation, which ignores most of the usual spawning requirements - including the gamerule; in any normal world virtually all the passive mobs that you encounter are spawned during world generation (in general they cannot spawn naturally since the mob cap is greatly exceeded):

[MC-56687 Passive mobs spawn despite /gamerule doMobSpawning false](https://bugs.mojang.com/browse/MC-56687)

This also affects mobs spawned from spawners, breeding, and anything else that is not "natural" spawning (for example, an iron farm will continue to spawn iron golems since they are spawned when certain requirements are met in a village, but a witch hut will not because the game just uses a structure-specific spawn list for naturally spawned mobs within their bounding box).

Mobs from mods may or may not follow the gamerule regardless of how they spawn (e.g. the mob creator may decide to check the gamerule before spawning a mob which is not naturally spawned. Also, while the link above is not considered to be a vanilla bug various exceptions are, [such as iron golems](https://bugs.mojang.com/browse/MC-111004))."
